[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cofecito              = "75upmoX4dfTqkRhhbbz2qfui8yxuVYzcyQgwEnhA8Vs2"
traceability_registry = "DkfahgAG9QdVYiDPeHaMgkoawPBjLh7sjeDVsN2p7Y3E"
qr_redeem             = "8Va7rSi8sCXgFzgDgLAy9UkrhHkH1NtKW286zPDDaA6f"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
